const COURT_QUESTIONS = [
  'Ai có khả năng nói “5 phút nữa tới” khi vẫn còn đang nằm nhất?',
  'Ai vào quán gọi món lâu nhất nhưng cuối cùng gọi giống người bên cạnh?',
  'Ai dễ bị dụ mua một món chỉ vì bao bì đẹp nhất?',
  'Ai có thể ngủ quên giữa lúc cả nhóm đang cãi nhau?',
  'Ai mở điện thoại để xem giờ rồi quên luôn mình định xem gì?',
  'Ai có khả năng bí mật ăn hết đồ ăn chung nhất?',
  'Ai nhắn “ừ” nghe đáng sợ hơn cả một bài văn dài?',
  'Ai hay kể chuyện dài nhưng quên mất đoạn kết nhất?',
  'Ai có khả năng sống sót lâu nhất nếu cả nhóm lạc trên đảo?',
  'Ai sẽ là người đầu tiên bán đứng cả nhóm để đổi lấy trà sữa?',
  'Ai nói “không sao đâu” nhưng mặt thể hiện có rất nhiều sao?',
  'Ai có khả năng đi nhầm ngày hẹn nhất?',
  'Ai chụp 50 tấm rồi vẫn bảo chưa có tấm nào đẹp?',
  'Ai cười trước khi kể xong chuyện nên chẳng ai hiểu?',
  'Ai có thể biến một việc năm phút thành dự án cả ngày?',
  'Ai hay đưa lời khuyên rất hay nhưng chưa bao giờ tự làm?',
  'Ai có khả năng làm giàu đầu tiên nhờ một ý tưởng kỳ quặc?',
  'Ai sẽ mang vali to nhất cho chuyến đi hai ngày?',
  'Ai có khả năng gọi đồ cay rồi xin nước đầu tiên?',
  'Ai là người dễ bị phát hiện nói dối nhất?',
  'Ai có thể tranh luận với Google và vẫn tin mình đúng?',
  'Ai hay nói “tùy” nhưng bác hết mọi lựa chọn?',
  'Ai có khả năng kết bạn với người lạ nhanh nhất?',
  'Ai dễ trở thành nhân vật chính trong một drama vô tri?',
  'Ai có thể ăn sáng lúc ba giờ chiều mà không thấy sai?',
  'Ai có thư viện ảnh toàn ảnh chụp màn hình không bao giờ xem lại?',
  'Ai dễ quên mật khẩu vừa mới đổi nhất?',
  'Ai có thể xem một tập phim rồi thức tới sáng?',
  'Ai hay mang sạc nhưng điện thoại lúc nào cũng còn 2%?',
  'Ai có khả năng đến tiệc chỉ để ăn rồi âm thầm biến mất?',
  'Ai sẽ thắng cuộc thi viện lý do đi trễ?',
  'Ai dễ bị chó mèo ngoài đường dụ đi theo nhất?',
  'Ai có thể mua đồ vì giảm giá dù không biết dùng làm gì?',
  'Ai sẽ khóc đầu tiên khi xem phim hoạt hình?',
  'Ai có khả năng trở thành streamer bất ngờ nổi tiếng?',
  'Ai nói chuyện với đồ vật khi chúng không hoạt động?',
  'Ai có thể quên tên người vừa được giới thiệu?',
  'Ai hay đặt báo thức nhiều nhất nhưng vẫn dậy muộn?',
  'Ai có khả năng lấy nhầm dép ở một bữa tiệc?',
  'Ai sẽ chuẩn bị kế hoạch chi tiết rồi làm hoàn toàn khác?',
  'Ai có thể biến một tấm ảnh bình thường thành meme của nhóm?',
  'Ai dễ cười trong tình huống cần nghiêm túc nhất?',
  'Ai có khả năng bị lạc ngay trong trung tâm thương mại?',
  'Ai luôn biết quán ăn ngon nhưng không nhớ địa chỉ?',
  'Ai có thể nghe một bài hát lặp lại cả tuần?',
  'Ai dễ tin tin nhắn “bạn đã trúng thưởng” nhất?',
  'Ai sẽ xin một miếng rồi ăn hết nửa phần?',
  'Ai có khả năng quên mình đang để kính trên đầu?',
  'Ai hay bảo tiết kiệm rồi đặt hàng lúc nửa đêm?',
  'Ai sẽ trở thành trưởng nhóm dù không ai bầu?',
  'Ai có thể biến buổi họp nghiêm túc thành tiết mục hài?',
  'Ai sẽ mang đồ ăn tới nhưng quên mang chính mình đúng giờ?',
  'Ai dễ bị bắt gặp đang tự diễn một cuộc hội thoại?',
  'Ai có khả năng làm hỏng bí mật vì quá háo hức?',
  'Ai luôn chọn hàng thanh toán chậm nhất?',
  'Ai có thể ngủ ở bất kỳ đâu, bất kỳ tư thế nào?',
  'Ai sẽ dùng hết pin để chụp ảnh trước khi chuyến đi bắt đầu?',
  'Ai có khả năng nói “một ván cuối” thêm mười lần?',
  'Ai dễ đổi ý ngay sau khi món ăn được mang ra?',
  'Ai xứng đáng nhận danh hiệu “nhân vật khó đoán nhất nhóm”?',
];

const WRITER_QUESTIONS = [
  'Nếu nhóm mình là một công ty, sản phẩm vô dụng nhất sẽ là gì?',
  'Viết một lý do thật sang để giải thích việc đi trễ.',
  'Đặt tên cho bộ phim kể về nhóm mình.',
  'Nếu bị người ngoài hành tinh bắt, câu đầu tiên bạn sẽ nói là gì?',
  'Viết khẩu hiệu tranh cử lớp trưởng tệ nhất có thể.',
  'Món ăn nào mô tả đúng tính cách bạn nhất, và vì sao?',
  'Một siêu năng lực nghe hay nhưng dùng cực bất tiện là gì?',
  'Tên Wi-Fi nào khiến hàng xóm hoang mang nhất?',
  'Nếu được đổi tên một ngày, bạn sẽ chọn tên gì?',
  'Điều đáng ngờ nhất có thể nói trong thang máy là gì?',
  'Một công việc bạn chắc chắn bị đuổi ngay ngày đầu?',
  'Viết tiêu đề báo ngày mai về một người trong nhóm.',
  'Nếu con mèo biết nói, điều đầu tiên nó tố cáo bạn là gì?',
  'Một món quà sinh nhật khiến người nhận phải suy nghĩ rất lâu?',
  'Tên quán trà sữa do nhóm mình mở sẽ là gì?',
  'Câu nào không nên nói trong lần đầu gặp phụ huynh người yêu?',
  'Nếu cuộc đời có nút hoàn tác, bạn dùng cho chuyện gì hôm nay?',
  'Phát minh nào giải quyết một vấn đề không ai gặp?',
  'Viết câu mở đầu cho cuốn tự truyện của bạn.',
  'Nếu điện thoại được làm nhân chứng, nó sẽ khai gì?',
  'Một luật mới bạn muốn áp dụng riêng cho nhóm này?',
  'Đặt biệt danh cho con gián vừa chạy qua phòng.',
  'Một cách cực tệ để gây ấn tượng trong buổi phỏng vấn?',
  'Nếu trở thành giáo viên, môn học kỳ lạ bạn sẽ dạy là gì?',
  'Nội dung tin nhắn cuối cùng trước ngày tận thế?',
  'Một ứng dụng không ai cần nhưng bạn vẫn muốn tải?',
  'Nếu được thêm một món vào menu mọi quán, đó là gì?',
  'Câu quảng cáo chân thật nhất cho bản thân bạn?',
  'Một dấu hiệu cho thấy buổi đi chơi sắp thành thảm họa?',
  'Nếu nhóm có linh vật, nó sẽ là con gì và mang vẻ mặt nào?',
  'Viết một lời xin lỗi không có vẻ gì là xin lỗi.',
  'Một bí quyết làm giàu chắc chắn không hiệu quả?',
  'Nếu chỉ được dùng ba từ trong cả ngày, bạn chọn từ nào?',
  'Tên một chương trình truyền hình thực tế về nhóm mình?',
  'Một câu nên in lên áo đồng phục của nhóm?',
  'Nếu có thể cấm một âm thanh, bạn sẽ cấm âm thanh nào?',
  'Một lý do để từ chối cuộc gọi mà không ai tin?',
  'Nếu hôm nay là một loại thời tiết, nó là gì?',
  'Món đồ nào nên có chế độ máy bay?',
  'Nếu thú cưng được chấm điểm bạn, bạn được mấy điểm?',
  'Viết review một sao cho ngày hôm nay.',
  'Một điều bạn sẽ làm nếu vô hình trong đúng năm phút?',
  'Nếu phải mở bảo tàng, bạn sẽ trưng bày bộ sưu tập gì?',
  'Câu thần chú để gọi đồ ăn xuất hiện?',
  'Nếu nhóm mình có quốc ca, câu đầu tiên là gì?',
  'Một thử thách kỳ quặc bạn tin mình sẽ vô địch?',
  'Tên món cocktail mô tả tuần vừa rồi của bạn?',
  'Nếu được gửi tin nhắn cho mình của năm năm trước, bạn nhắn gì?',
  'Một cách dùng hoàn toàn sai cho chiếc ô?',
  'Nếu được làm ma, bạn sẽ ám ở đâu?',
  'Cái tên tệ nhất cho một đứa trẻ siêu anh hùng?',
  'Viết câu cuối cùng của một bộ phim cực kỳ khó hiểu.',
  'Nếu não có lịch sử tìm kiếm, mục gần nhất là gì?',
  'Một giải thưởng bạn xứng đáng nhận nhưng chưa ai trao?',
  'Nếu mở khóa học online, bạn sẽ dạy kỹ năng gì?',
  'Một món ăn bạn sẵn sàng bảo vệ tới cùng?',
  'Nếu cả nhóm đổi nghề, nghề chung phù hợp nhất là gì?',
  'Viết trạng thái mạng xã hội của một con cá.',
  'Một câu có thể nói khi chơi game nhưng không nên nói trong đám cưới?',
  'Nếu tối nay phải lên sân khấu, tiết mục của bạn là gì?',
];

const WORD_PAIRS = [
  ['cà phê', 'trà sữa'], ['mèo', 'chó'], ['mưa', 'nắng'], ['bánh mì', 'hamburger'],
  ['xe máy', 'xe đạp'], ['TikTok', 'YouTube'], ['biển', 'hồ bơi'], ['phở', 'bún bò'],
  ['điện thoại', 'máy tính bảng'], ['Đà Lạt', 'Sa Pa'], ['kem', 'sữa chua'], ['bác sĩ', 'y tá'],
  ['karaoke', 'hòa nhạc'], ['Tết', 'sinh nhật'], ['cơm tấm', 'cơm gà'], ['siêu thị', 'chợ'],
  ['máy lạnh', 'quạt máy'], ['Facebook', 'Instagram'], ['gà rán', 'khoai tây chiên'], ['sư tử', 'hổ'],
  ['mặt trăng', 'mặt trời'], ['taxi', 'xe buýt'], ['bút chì', 'bút bi'], ['mì gói', 'mì Ý'],
  ['phim kinh dị', 'phim hài'], ['bóng đá', 'bóng rổ'], ['khách sạn', 'homestay'], ['núi', 'đồi'],
  ['nước ngọt', 'nước ép'], ['shopee', 'tiki'], ['cầu thang', 'thang máy'], ['sách', 'truyện tranh'],
  ['vàng', 'bạc'], ['pizza', 'bánh tráng'], ['chuột', 'bàn phím'], ['đám cưới', 'tiệc sinh nhật'],
  ['áo mưa', 'ô'], ['nồi cơm', 'lò vi sóng'], ['giày', 'dép'], ['camera', 'gương'],
];

const CHALLENGES = [
  'Tạo dáng như ảnh thẻ nhưng phải thật tự tin trong 10 giây.',
  'Nói lời cảm ơn chiếc ghế đang ngồi bằng giọng trang trọng.',
  'Hát một câu bất kỳ như đang biểu diễn ở sân vận động.',
  'Dùng ba từ để quảng cáo người ngồi gần bạn nhất.',
  'Kể một chuyện rất bình thường bằng giọng phim hành động.',
  'Đổi ảnh đại diện nhóm thành một emoji trong 3 phút nếu mọi người đồng ý.',
  'Nói tên ba món ăn liên tiếp mà không được cười.',
  'Tạo âm thanh thông báo điện thoại phiên bản của riêng bạn.',
  'Đọc câu “Tôi hoàn toàn vô tội” bằng ba cảm xúc khác nhau.',
  'Giả làm MC giới thiệu người vừa bỏ phiếu cho bạn.',
  'Nói một lời khen thật lòng cho người ít nói nhất nhóm.',
  'Diễn tả một con vật để cả nhóm đoán trong 20 giây.',
  'Giữ vẻ mặt nghiêm túc trong khi mọi người cố làm bạn cười.',
  'Bán chiếc dép gần nhất như một món đồ xa xỉ.',
  'Đặt một biệt danh dễ thương cho chính mình.',
  'Kể tên năm thứ màu vàng trong 10 giây.',
  'Nói một câu bằng giọng robot hết pin.',
  'Tạo một câu khẩu hiệu cho buổi chơi hôm nay.',
  'Diễn cảnh vừa trúng số nhưng không được phát ra tiếng.',
  'Mời cả nhóm uống nước bằng giọng hoàng gia.',
  'Tự chấm điểm khả năng đúng giờ của mình và giải thích.',
  'Nói nhanh ba lần “trà sữa trân châu trắng”.',
  'Chụp một kiểu ảnh cả nhóm thống nhất là “ảnh bìa album”.',
  'Kể một tài lẻ vô dụng nhưng đáng tự hào.',
  'Mô tả món ăn yêu thích mà không nói tên món.',
  'Giả làm tổng đài viên giải quyết khiếu nại “hôm nay quá nóng”.',
  'Đặt tên cho một ban nhạc gồm những người trong phòng.',
  'Nói câu xin lỗi vì đã quá đẹp trai hoặc xinh gái.',
  'Làm động tác ăn mừng chiến thắng trong năm giây.',
  'Chọn một người và đấu mắt trong 15 giây; ai cười trước thua.',
];

module.exports = { COURT_QUESTIONS, WRITER_QUESTIONS, WORD_PAIRS, CHALLENGES };
